// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://achnosgcorxugqovlvxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaG5vc2djb3J4dWdxb3ZsdnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDcyODQsImV4cCI6MjA1NzIyMzI4NH0.HrPawZi5-KD8t41m1WUKDXfur2ebLVryWb4__sstBBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);